### ISSUE TITLE
Compatability with 1.6

### ISSUE THREAD

**Issue by muyncky** [channelengine/prestashop#8]
In `ps_versions_compliancy` is defined that the module is compatible with PrestaShop 1.6. This is not true, the namespaces used in `channelengine/channelengine.php`, are not allowed in 1.6. We tested it in PrestaShop `1.6.1.11` and it did not work.
As far as I know, namespaces are introduced in PrestaShop 1.7.
Arrays are also defined as `$products = []`, this is also a feature that is not compatible with 1.6, the good ol' `array()` is necessary.

Is there a possibility that this module will be made compatible with 1.6? PrestaShop 1.6 will still be maintained well until the end of 2019. Seems quiet relevant to me ;-).

See the report here:
[channelengine_validation_20180206.pdf](https://github.com/channelengine/prestashop/files/1699817/channelengine_validation_20180206.pdf)

To check compatibility again go to https://validator.prestashop.com.

Thanks.

**Comment by christiaanderidder** [comment]
Hi muyncky,

We are currently working on an updated version of our extension which will contain many improvements. I will check whether 1.6 compatibility is one of them. However, we have used the current version of our extension successfully in 1.6 shops.

Did you get any php errors, or did it just not pass the compliancy test?

**Comment by muyncky** [comment]
The module page in the backoffice can not be loaded, it gives a fatal error, unexpected 'use', because of the namespaces. I installed it the regular way, by uploading the module in the backoffice.
Maybe you have a different approach?
